# Use root/example as user/password credentials
version: '3.1'

services:


  mongo:
    image: mongo
    restart: always
    env_file:
      - client-server.env

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - client-server.env
    ports:
      - "8081:8081"

  admin:
    image: devsav/admin-server
    restart: on-failure
    ports:
      - "9003:9003"

  client:
    image: devsav/client-service
    restart: on-failure
    env_file:
      - client-server.env
    depends_on:
      - mongo
    ports:
      - "8080:8080"