# Use root/example as user/password credentials
version: '3.1'

services:
  admin:
    image: devsav/admin-server
    restart: always
    ports:
      - "9003:9003"
    env_file:
      - client-server.env

  mongo:
    image: mongo
    restart: always
    env_file:
      - client-server.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - client-server.env

  client:
    image: devsav/client-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - admin
      - mongo
      - mongo-express
    env_file:
      - client-server.env